// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BarEchart: typeof import('./src/components/page-charts/src/bar-echart.vue')['default']
    BaseEchart: typeof import('./src/components/echarts/src/base-echart.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    HeaderCrumb: typeof import('./src/components/nav-header/c-cpns/header-crumb.vue')['default']
    HeaderInfo: typeof import('./src/components/nav-header/c-cpns/header-info.vue')['default']
    LineEchart: typeof import('./src/components/page-charts/src/line-echart.vue')['default']
    MapEchart: typeof import('./src/components/page-charts/src/map-echart.vue')['default']
    NavHeader: typeof import('./src/components/nav-header/nav-header.vue')['default']
    NavMenu: typeof import('./src/components/nav-menu/nav-menu.vue')['default']
    PageContent: typeof import('./src/components/page-content/page-content.vue')['default']
    PageModal: typeof import('./src/components/page-modal/page-modal.vue')['default']
    PageSearch: typeof import('./src/components/page-search/page-search.vue')['default']
    PieEchart: typeof import('./src/components/page-charts/src/pie-echart.vue')['default']
    RoseEchart: typeof import('./src/components/page-charts/src/rose-echart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
